server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://49.247.38.216:3306/jhjeon
    username: jhjeon
    password: jun24677
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

search:
  server:
    ip: 127.0.0.1

logging:
  config: classpath:logback.xml
  level:
    net:
      chndol:
        study:
          mybatissample:
            mapper: DEBUG